// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHZNb9xI59S0jBMm3xRot1HcFAjX82XQw',
    appId: '1:858851012397:web:d066c2cc54c29da0976da4',
    messagingSenderId: '858851012397',
    projectId: 'chatapp-ec119',
    authDomain: 'chatapp-ec119.firebaseapp.com',
    databaseURL: 'https://chatapp-ec119-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-ec119.appspot.com',
    measurementId: 'G-ZPVKPJJK9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_RDOSGL36nH5hfa76WuimzUqCeRi04n0',
    appId: '1:858851012397:android:362db9f2a8b92bef976da4',
    messagingSenderId: '858851012397',
    projectId: 'chatapp-ec119',
    databaseURL: 'https://chatapp-ec119-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-ec119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtPiGc1emgKN7hDmP6uVVTBThPFR41Sso',
    appId: '1:858851012397:ios:f089288ea9215946976da4',
    messagingSenderId: '858851012397',
    projectId: 'chatapp-ec119',
    databaseURL: 'https://chatapp-ec119-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-ec119.appspot.com',
    iosBundleId: 'com.example.chatterbox',
  );
}
